const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const {load,fakeRTDB,fakeDocument,root}=require('./helpers.cjs');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(){const runtime=load(),rtdb=fakeRTDB({siteMemos:{a:{text:'original',date:'2026-09-08',author:'A',projectTag:'ジムセレ',createdAt:'2026-09-08T01:00:00Z'}},staffProfiles:{s:{name:'Staff',profile:'profile',currentWork:'work',nextRequestDate:'2026-10-01'}},staffNotes:{l:{staffId:'s',text:'log',author:'A',createdAt:'2026-09-08T01:00:00Z'}}}),db=runtime.W.createDb(rtdb);const records=key=>Object.entries(rtdb.read(key)||{}).map(([id,value])=>{const doc={id,data:()=>value};return key==='siteMemos'?runtime.W.normalizeMemo(doc):key==='staffProfiles'?runtime.W.normalizeStaff(doc):runtime.W.normalizeComment(doc,key==='staffNotes'?'staffId':'memoId');});const ui=runtime.W.createRecordsUI({db:()=>db,records,loaded:()=>true,canWrite:()=>true,render(){}});return {...runtime,rtdb,db,ui,records};}
test('adapter awaits persisted additions and returns the generated id',async()=>{const {db,rtdb}=fixture();const ref=await db.collection('siteMemoComments').add({memoId:'a',text:'test',author:'A',createdAt:'date'});assert.equal(ref.id,'new1');assert.equal(rtdb.read('siteMemoComments/new1').text,'test');assert.equal((await db.collection('siteMemos').get()).docs[0].id,'a');});
test('unsubscribe detaches callbacks including an already queued initial snapshot',async()=>{const {db,rtdb}=fixture();let calls=0;const stop=db.collection('siteMemos').onSnapshot(()=>calls++);stop();await tick();rtdb.external('siteMemos/a/text','changed');assert.equal(calls,0);assert.equal(rtdb.listeners.get('siteMemos').size,0);});
test('non-overlapping edits preserve other fields, overlapping edits conflict atomically',async()=>{const {db,rtdb}=fixture();await db.doc('staffProfiles/s').updateChecked({profile:'new'},{profile:'profile'});assert.equal(rtdb.read('staffProfiles/s').nextRequestDate,'2026-10-01');await assert.rejects(db.doc('staffProfiles/s').updateChecked({profile:'stale'},{profile:'profile'}),err=>err.code==='conflict');assert.equal(rtdb.read('staffProfiles/s').profile,'new');});
test('two simultaneous saves cannot silently overwrite the same field',async()=>{const {db,rtdb}=fixture();const out=await Promise.allSettled(['one','two'].map(text=>db.doc('siteMemos/a').updateChecked({text},{text:'original'})));assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal(out.filter(x=>x.status==='rejected').length,1);assert.equal(rtdb.read('siteMemos/a').text,'one');});
test('editing a remotely deleted record never recreates it and preserves its draft',async()=>{const {ui,rtdb}=fixture();ui.startEdit('memo','a');ui.input('memo','a','text','my unsaved work');rtdb.external('siteMemos/a',null);await ui.saveEdit('memo','a');assert.equal(rtdb.read('siteMemos/a'),null);assert.equal(ui.drafts.get('memo:a').draft.text,'my unsaved work');assert.match(ui.drafts.get('memo:a').msg,/削除/);});
test('editing only a memo body does not overwrite a remotely updated author',async()=>{const {ui,rtdb}=fixture();ui.startEdit('memo','a');ui.input('memo','a','text','new body');rtdb.external('siteMemos/a/author','Other');await ui.saveEdit('memo','a');assert.equal(rtdb.read('siteMemos/a').author,'Other');assert.equal(rtdb.read('siteMemos/a').text,'new body');});
test('saving one editor never clears a different record draft',async()=>{const {ui}=fixture();ui.startEdit('memo','a');ui.input('memo','a','text','new');const saving=ui.saveEdit('memo','a');ui.startEdit('staff','s');ui.input('staff','s','name','draft staff');await saving;assert.equal(ui.drafts.get('staff:s').draft.name,'draft staff');});
test('comment input event names match the rendered form and a double submit adds once',async()=>{const {ui,rtdb}=fixture();const doc=fakeDocument('<div id="root"></div>'),rootEl=doc.getElementById('root');ui.bind(rootEl);ui.openComposer('comment','a');const html=ui.thread('comment','a');assert.match(html,/data-wb-compose="text"/);await rootEl.dispatch('input',{target:{dataset:{wbCompose:'text',kind:'comment',id:'a'},value:'actual typed comment'}});await rootEl.dispatch('input',{target:{dataset:{wbCompose:'author',kind:'comment',id:'a'},value:'Writer'}});await Promise.all([ui.submit('comment','a'),ui.submit('comment','a')]);const saved=Object.values(rtdb.read('siteMemoComments'));assert.equal(saved.length,1);assert.equal(saved[0].text,'actual typed comment');assert.equal(saved[0].author,'Writer');assert.equal(saved[0].memoId,'a');});
test('failed comment and profile saves retain input and release busy state',async()=>{const {ui,rtdb}=fixture();ui.openComposer('staffnote','s');ui.input('staffnote','s','text','request draft',true);ui.startEdit('staff','s');ui.input('staff','s','profile','unsaved profile');rtdb.fail(true);await ui.submit('staffnote','s');await ui.saveEdit('staff','s');assert.equal(ui.composers.get('staffnote:s').draft.text,'request draft');assert.equal(ui.composers.get('staffnote:s').busy,false);assert.equal(ui.drafts.get('staff:s').draft.profile,'unsaved profile');assert.equal(ui.drafts.get('staff:s').busy,false);});
test('two-click deletion is scoped to the target and cleans up its timer on reset/dispose',()=>{const {W,clock}=load();let updates=0;const arm=W.createDeleteArm(()=>updates++);assert.equal(arm.press('a'),false);assert.equal(clock.jobs.size,1);assert.equal(arm.press('b'),false);assert.equal(clock.jobs.size,1);assert.equal(arm.isArmed('a'),false);assert.equal(arm.press('b'),true);assert.equal(clock.jobs.size,0);arm.press('c');arm.reset();assert.equal(clock.jobs.size,0);arm.press('d');arm.dispose();assert.equal(clock.jobs.size,0);assert.equal(arm.press('d'),false);assert(updates>0);});
test('staff log deletion failure is caught; leaving the section resets confirmation',async()=>{const {ui,rtdb,clock}=fixture();await ui.removeLog('l');assert.equal(clock.jobs.size,1);ui.resetConfirmation();assert.equal(clock.jobs.size,0);await ui.removeLog('l');rtdb.fail(true);await ui.removeLog('l');assert.equal(rtdb.read('staffNotes/l').text,'log');assert.match(ui.thread('staffnote','s'),/保存できませんでした/);});
test('threads collapse past 10 entries and expand in full on demand',()=>{const {ui,rtdb}=fixture();for(let i=0;i<14;i++)rtdb.external('staffNotes/gen'+i,{staffId:'s',text:'entry'+i,author:'A',createdAt:'2026-09-08T02:'+String(i).padStart(2,'0')+':00Z'});const collapsed=ui.thread('staffnote','s');assert.equal((collapsed.match(/class="comment-text"/g)||[]).length,10);assert.match(collapsed,/さらに表示（残り5件）/);const untouched=ui.thread('comment','a');assert.equal((untouched.match(/data-wb-action="compose"/g)||[]).length,1);ui.expandThread('staffnote','s');const expanded=ui.thread('staffnote','s');assert.equal((expanded.match(/class="comment-text"/g)||[]).length,15);assert.doesNotMatch(expanded,/さらに表示/);});
test('long memo/log bodies collapse to a 20-char preview and expand on demand',()=>{const {ui}=fixture();const longText='0123456789'.repeat(3);const memoRecord={id:'m1',text:longText,date:'2026-09-08',author:'A',createdAt:'2026-09-08T01:00:00Z'};const collapsed=ui.memo(memoRecord);assert.match(collapsed,/続きを見る/);assert.equal(collapsed.includes(longText),false);assert.match(collapsed,new RegExp(longText.slice(0,20)+'…'));ui.expandText('memo','m1');const expanded=ui.memo(memoRecord);assert.equal(expanded.includes(longText),true);assert.match(expanded,/閉じる/);ui.collapseText('memo','m1');assert.match(ui.memo(memoRecord),/続きを見る/);const shortMemo=ui.memo({id:'a',text:'short',date:'2026-09-08',author:'A',createdAt:'2026-09-08T01:00:00Z'});assert.doesNotMatch(shortMemo,/続きを見る/);});
test('task log transactions append to the latest array instead of losing concurrent logs',async()=>{const {db,rtdb}=fixture();rtdb.external('tasks/t',{title:'Task',logs:[]});await Promise.all(['A','B'].map(text=>db.doc('tasks/t').mutate(current=>({...current,logs:current.logs.concat({text,date:'2026-09-08'})}))));assert.equal(rtdb.read('tasks/t').logs.map(x=>x.text).join(','),'A,B');});
test('manual legacy migration is idempotent and cannot overwrite an edited memo',async()=>{const {db,rtdb}=fixture();assert.equal(await db.doc('siteMemos/a').createIfAbsent({text:'legacy'}),false);assert.equal(rtdb.read('siteMemos/a').text,'original');assert.equal(await db.doc('siteMemos/new').createIfAbsent({text:'legacy'}),true);assert.equal(await db.doc('siteMemos/new').createIfAbsent({text:'legacy'}),false);});
test('focused Japanese input is not detached or replaced during a live render',()=>{const active={tagName:'TEXTAREA',getAttribute:()=>null};let replacements=0,creates=0;const rootEl={contains:n=>n===active,querySelectorAll:()=>[],addEventListener(){},replaceChildren(){replacements++;}};const {W}=load({document:{activeElement:active,createElement(){creates++;throw Error('Must not detach composing input');}}});W.replaceContent(rootEl,'latest server markup');assert.equal(replacements,0);assert.equal(creates,0);assert.equal(rootEl._pendingMarkup,'latest server markup');});
test('memo dates use local days and project aliases stay compatible',()=>{const {W}=load();assert.equal(W.canonicalProject('共通・インフラ'),'共通/インフラ');assert.equal(W.createdDay('invalid'),'');assert.equal(W.esc('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');const list=[{id:'a',date:'2026-09-01',createdAt:''},{id:'b',date:'2026-09-02',createdAt:''}];assert.equal(W.sortMemos(list).map(n=>n.id).join(','),'b,a');assert.equal(W.sortMemos(list,'oldest').map(n=>n.id).join(','),'a,b');});
for(const page of ['index','notes'])test(page+' script starts with all real HTML ids and cleans up subscriptions on pagehide',async()=>{
 const doc=fakeDocument(fs.readFileSync(path.join(root,page+'.html'),'utf8')),rtdb=fakeRTDB(),events=new Map();let authHandler,anonymousCalls=0,signOutCalls=0;
 const user={uid:'google-user',email:'cogweb39@gmail.com',displayName:'User',isAnonymous:false};
 const auth={currentUser:user,onAuthStateChanged:fn=>{authHandler=fn;return()=>{};},signInAnonymously:async()=>{anonymousCalls++;},signOut:async()=>{signOutCalls++;},signInWithPopup:async()=>{}};
 const firebase={initializeApp(){},database:()=>rtdb,auth:()=>auth};firebase.auth.GoogleAuthProvider=function(){};
 const {context,clock}=load({document:doc,firebase,WorkboardFirebase:{},localStorage:{getItem:()=>'',setItem(){}},navigator:{},location:{reload(){}},addEventListener:(key,fn)=>events.set(key,fn)});
 vm.runInContext(fs.readFileSync(path.join(root,'assets',page+'-app.js'),'utf8'),context,{filename:page+'-app.js'});
 authHandler(user);await tick();await tick();
 assert.equal(anonymousCalls,0);assert.equal(signOutCalls,0);
 if(page==='index'){const date=doc.getElementById('boardDate');assert.match(date.value,/^\d{4}-\d{2}-\d{2}$/);auth.currentUser={uid:'anon',isAnonymous:true};authHandler(auth.currentUser);assert.equal(signOutCalls,0);assert.equal(doc.getElementById('appRoot').hidden,true);}
 events.get('pagehide')();assert([...rtdb.listeners.values()].every(set=>set.size===0));assert.equal(clock.jobs.size,0);
});
